// Generated by `cargo xtask weaver generate` from lablet/telemetry/registry/; don't edit.

//! Attribute keys: lablet's own, and every semantic-convention attribute that
//! a lablet span, event, or resource carries.

/// Describes a class of error the operation ended with.
pub const ERROR_TYPE: &str = "error.type";

/// The exception message.
pub const EXCEPTION_MESSAGE: &str = "exception.message";

/// The type of the exception (its fully-qualified class name, if applicable). The dynamic type of the exception should be preferred over the static type in languages that support it.
pub const EXCEPTION_TYPE: &str = "exception.type";

/// Human-readable name of the GenAI agent provided by the application.
pub const GEN_AI_AGENT_NAME: &str = "gen_ai.agent.name";

/// The version of the GenAI agent.
pub const GEN_AI_AGENT_VERSION: &str = "gen_ai.agent.version";

/// The unique identifier for a conversation (session, thread), used to store and correlate messages within this conversation.
pub const GEN_AI_CONVERSATION_ID: &str = "gen_ai.conversation.id";

/// The chat history provided to the model as an input.
pub const GEN_AI_INPUT_MESSAGES: &str = "gen_ai.input.messages";

/// The name of the operation being performed.
pub const GEN_AI_OPERATION_NAME: &str = "gen_ai.operation.name";

/// Messages returned by the model where each message represents a specific model response (choice, candidate).
pub const GEN_AI_OUTPUT_MESSAGES: &str = "gen_ai.output.messages";

/// The Generative AI provider as identified by the client or server instrumentation.
pub const GEN_AI_PROVIDER_NAME: &str = "gen_ai.provider.name";

/// The maximum number of tokens the model generates for a request.
pub const GEN_AI_REQUEST_MAX_TOKENS: &str = "gen_ai.request.max_tokens";

/// The name of the GenAI model a request is being made to.
pub const GEN_AI_REQUEST_MODEL: &str = "gen_ai.request.model";

/// The reasoning or thinking effort level requested for a GenAI model.
pub const GEN_AI_REQUEST_REASONING_LEVEL: &str = "gen_ai.request.reasoning.level";

/// Requests with same seed value more likely to return same result.
pub const GEN_AI_REQUEST_SEED: &str = "gen_ai.request.seed";

/// The temperature setting for the GenAI request.
pub const GEN_AI_REQUEST_TEMPERATURE: &str = "gen_ai.request.temperature";

/// Array of reasons the model stopped generating tokens, corresponding to each generation received.
pub const GEN_AI_RESPONSE_FINISH_REASONS: &str = "gen_ai.response.finish_reasons";

/// The unique identifier for the completion.
pub const GEN_AI_RESPONSE_ID: &str = "gen_ai.response.id";

/// The name of the model that generated the response.
pub const GEN_AI_RESPONSE_MODEL: &str = "gen_ai.response.model";

/// The system message or instructions provided to the GenAI model separately from the chat history.
pub const GEN_AI_SYSTEM_INSTRUCTIONS: &str = "gen_ai.system_instructions";

/// Parameters passed to the tool call.
pub const GEN_AI_TOOL_CALL_ARGUMENTS: &str = "gen_ai.tool.call.arguments";

/// The tool call identifier.
pub const GEN_AI_TOOL_CALL_ID: &str = "gen_ai.tool.call.id";

/// The result returned by the tool call (if any and if execution was successful).
pub const GEN_AI_TOOL_CALL_RESULT: &str = "gen_ai.tool.call.result";

/// The tool description.
pub const GEN_AI_TOOL_DESCRIPTION: &str = "gen_ai.tool.description";

/// Name of the tool utilized by the agent.
pub const GEN_AI_TOOL_NAME: &str = "gen_ai.tool.name";

/// Type of the tool utilized by the agent
pub const GEN_AI_TOOL_TYPE: &str = "gen_ai.tool.type";

/// The number of input tokens served from a provider-managed cache.
pub const GEN_AI_USAGE_CACHE_READ_INPUT_TOKENS: &str = "gen_ai.usage.cache_read.input_tokens";

/// The number of input tokens written to a provider-managed cache.
pub const GEN_AI_USAGE_CACHE_WRITE_INPUT_TOKENS: &str = "gen_ai.usage.cache_write.input_tokens";

/// The number of tokens used in the GenAI input (prompt).
pub const GEN_AI_USAGE_INPUT_TOKENS: &str = "gen_ai.usage.input_tokens";

/// The number of tokens used in the GenAI response (completion).
pub const GEN_AI_USAGE_OUTPUT_TOKENS: &str = "gen_ai.usage.output_tokens";

/// A string representation of the `id` property of the request and its corresponding response.
pub const JSONRPC_REQUEST_ID: &str = "jsonrpc.request.id";

/// One-based attempt number of a provider call within its turn.
pub const LABLET_ATTEMPT: &str = "lablet.attempt";

/// SHA-256 of the resolved config, in hex.
pub const LABLET_CONFIG_DIGEST: &str = "lablet.config.digest";

/// Names of the configured MCP servers.
pub const LABLET_MCP_SERVERS: &str = "lablet.mcp.servers";

/// Size of the system prompt in bytes, skills included.
pub const LABLET_PROMPT_SYSTEM_BYTES: &str = "lablet.prompt.system_bytes";

/// Size of the task prompt in bytes.
pub const LABLET_PROMPT_USER_BYTES: &str = "lablet.prompt.user_bytes";

/// Number of provider calls that returned a completion.
pub const LABLET_PROVIDER_CALLS: &str = "lablet.provider.calls";

/// Latency of the slowest provider call attempt, in milliseconds.
pub const LABLET_PROVIDER_LATENCY_MS_MAX: &str = "lablet.provider.latency_ms.max";

/// Sum of the latencies of every provider call attempt, in milliseconds.
pub const LABLET_PROVIDER_LATENCY_MS_TOTAL: &str = "lablet.provider.latency_ms.total";

/// Number of provider call attempts made beyond the first of their call.
pub const LABLET_PROVIDER_RETRIES: &str = "lablet.provider.retries";

/// Size in bytes of the system prompt, messages, and tool specs sent in a provider call.
pub const LABLET_REQUEST_BYTES: &str = "lablet.request.bytes";

/// Whether the run produced a structured result, the `task_complete` argument.
pub const LABLET_RESULT_HAS_STRUCTURED: &str = "lablet.result.has_structured";

/// The structured result, the `task_complete` argument, as a JSON string.
pub const LABLET_RESULT_STRUCTURED: &str = "lablet.result.structured";

/// The final assistant text.
pub const LABLET_RESULT_TEXT: &str = "lablet.result.text";

/// Size of the final assistant text in bytes.
pub const LABLET_RESULT_TEXT_BYTES: &str = "lablet.result.text_bytes";

/// How long the loop waits before the next attempt, in milliseconds.
pub const LABLET_RETRY_BACKOFF_MS: &str = "lablet.retry.backoff_ms";

/// Whether the failed provider call is retried.
pub const LABLET_RETRY_WILL_RETRY: &str = "lablet.retry.will_retry";

/// How the run decides that the model has finished.
pub const LABLET_RUN_COMPLETION_MODE: &str = "lablet.run.completion_mode";

/// Cost of the run in US dollars, from the configured pricing.
pub const LABLET_RUN_COST_USD: &str = "lablet.run.cost_usd";

/// Wall-clock duration of the run, in milliseconds.
pub const LABLET_RUN_DURATION_MS: &str = "lablet.run.duration_ms";

/// The message of the error that ended the run.
pub const LABLET_RUN_ERROR: &str = "lablet.run.error";

/// The configured cap on turns.
pub const LABLET_RUN_MAX_TURNS: &str = "lablet.run.max_turns";

/// Why the run ended.
pub const LABLET_RUN_STOP_REASON: &str = "lablet.run.stop_reason";

/// The configured run timeout, in milliseconds.
pub const LABLET_RUN_TIMEOUT_MS: &str = "lablet.run.timeout_ms";

/// Where the run's transcript was written.
pub const LABLET_RUN_TRANSCRIPT_PATH: &str = "lablet.run.transcript_path";

/// Number of turns the run took.
pub const LABLET_RUN_TURNS: &str = "lablet.run.turns";

/// Number of skill files appended to the system prompt.
pub const LABLET_SKILLS_COUNT: &str = "lablet.skills.count";

/// Number of calls to one tool, `<key>` being the tool name.
///
/// A template: the emitted key is this prefix, a dot, and `<key>`.
pub const LABLET_TOOL_CALLS: &str = "lablet.tool.calls";

/// Number of error results from one tool, `<key>` being the tool name.
///
/// A template: the emitted key is this prefix, a dot, and `<key>`.
pub const LABLET_TOOL_ERRORS: &str = "lablet.tool.errors";

/// Size of a tool call's input in bytes.
pub const LABLET_TOOL_INPUT_BYTES: &str = "lablet.tool.input.bytes";

/// Whether the tool call returned an error result to the model.
pub const LABLET_TOOL_IS_ERROR: &str = "lablet.tool.is_error";

/// Sum of the latencies of the calls to one tool, in milliseconds, `<key>` being the tool name.
///
/// A template: the emitted key is this prefix, a dot, and `<key>`.
pub const LABLET_TOOL_LATENCY_MS: &str = "lablet.tool.latency_ms";

/// Size of a tool call's output in bytes.
pub const LABLET_TOOL_OUTPUT_BYTES: &str = "lablet.tool.output.bytes";

/// Where a tool comes from.
pub const LABLET_TOOL_SOURCE: &str = "lablet.tool.source";

/// Number of tool calls that returned an error result.
pub const LABLET_TOOL_CALLS_ERRORS: &str = "lablet.tool_calls.errors";

/// Sum of the sizes of every tool call's input, in bytes.
pub const LABLET_TOOL_CALLS_INPUT_BYTES_TOTAL: &str = "lablet.tool_calls.input_bytes.total";

/// Sum of the latencies of every tool call, in milliseconds.
pub const LABLET_TOOL_CALLS_LATENCY_MS_TOTAL: &str = "lablet.tool_calls.latency_ms.total";

/// Sum of the sizes of every tool call's output, in bytes.
pub const LABLET_TOOL_CALLS_OUTPUT_BYTES_TOTAL: &str = "lablet.tool_calls.output_bytes.total";

/// Number of tool calls executed. The intercepted `task_complete` call isn't one.
pub const LABLET_TOOL_CALLS_TOTAL: &str = "lablet.tool_calls.total";

/// Number of tool calls that named a tool the run didn't offer.
pub const LABLET_TOOL_CALLS_UNKNOWN: &str = "lablet.tool_calls.unknown";

/// Number of tools offered to the model.
pub const LABLET_TOOLS_COUNT: &str = "lablet.tools.count";

/// Names of the tools offered to the model, after the allow and deny lists.
pub const LABLET_TOOLS_NAMES: &str = "lablet.tools.names";

/// One-based index of the turn a provider call or tool call belongs to.
pub const LABLET_TURN: &str = "lablet.turn";

/// The name of the request or notification method.
pub const MCP_METHOD_NAME: &str = "mcp.method.name";

/// The [version](https://modelcontextprotocol.io/specification/versioning) of the Model Context Protocol used.
pub const MCP_PROTOCOL_VERSION: &str = "mcp.protocol.version";

/// Identifies [MCP session](https://modelcontextprotocol.io/specification/2025-06-18/basic/transports#session-management).
pub const MCP_SESSION_ID: &str = "mcp.session.id";

/// [OSI transport layer](https://wikipedia.org/wiki/Transport_layer) or [inter-process communication method](https://wikipedia.org/wiki/Inter-process_communication).
pub const NETWORK_TRANSPORT: &str = "network.transport";

/// Status code of the RPC returned by the RPC server or generated by the client
pub const RPC_RESPONSE_STATUS_CODE: &str = "rpc.response.status_code";

/// Server domain name if available without reverse DNS lookup; otherwise, IP address or UNIX domain socket name.
pub const SERVER_ADDRESS: &str = "server.address";

/// Server port number.
pub const SERVER_PORT: &str = "server.port";

/// The operational criticality of the service.
pub const SERVICE_CRITICALITY: &str = "service.criticality";

/// Logical name of the service.
pub const SERVICE_NAME: &str = "service.name";

/// The version string of the service component. The format is not defined by these conventions.
pub const SERVICE_VERSION: &str = "service.version";

/// A unique ID to identify a session.
pub const SESSION_ID: &str = "session.id";

/// The language of the telemetry SDK.
pub const TELEMETRY_SDK_LANGUAGE: &str = "telemetry.sdk.language";

/// The name of the telemetry SDK as defined above.
pub const TELEMETRY_SDK_NAME: &str = "telemetry.sdk.name";

/// The version string of the telemetry SDK.
pub const TELEMETRY_SDK_VERSION: &str = "telemetry.sdk.version";
