// Generated by `cargo xtask weaver generate` from lablet/telemetry/registry/; don't edit.

//! The closed value sets: one enum for each lablet attribute whose type is a
//! list of members.

/// How the run decides that the model has finished.
///
/// The values of `lablet.run.completion_mode`.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum LabletRunCompletionMode {
    /// The run completes when the model returns a turn with no tool calls.
    Natural,
    /// The run completes when the model calls `task_complete`.
    Explicit,
}

impl LabletRunCompletionMode {
    /// The value as it appears on the wire.
    #[must_use]
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::Natural => "natural",
            Self::Explicit => "explicit",
        }
    }
}

impl core::fmt::Display for LabletRunCompletionMode {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        f.write_str(self.as_str())
    }
}

/// Why the run ended.
///
/// The values of `lablet.run.stop_reason`.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum LabletRunStopReason {
    /// The model finished, by a turn with no tool calls or by calling `task_complete`.
    Completed,
    /// In explicit mode, the model returned a turn with no tool calls and never called `task_complete`.
    EndedWithoutCompletion,
    /// The run reached `run.max_turns`.
    MaxTurns,
    /// The run reached `run.timeout`.
    Timeout,
    /// Input plus output tokens reached `run.max_total_tokens`.
    MaxTotalTokens,
    /// The last response hit the output token limit. Its tool calls, if any, weren't executed.
    OutputTruncated,
    /// The conversation outgrew the model's context. The provider rejected the request as too long, or cut the response short at the window.
    ContextExhausted,
    /// One provider call failed on every attempt `run.max_retries` allows.
    RetriesExhausted,
    /// Consecutive tool error results reached `run.max_consecutive_tool_errors`.
    ToolErrorsExhausted,
    /// The run was cancelled.
    Cancelled,
    /// The provider returned an error that isn't retryable.
    ProviderError,
    /// The model declined to answer, or a content filter withheld the response.
    Refused,
}

impl LabletRunStopReason {
    /// The value as it appears on the wire.
    #[must_use]
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::Completed => "completed",
            Self::EndedWithoutCompletion => "ended_without_completion",
            Self::MaxTurns => "max_turns",
            Self::Timeout => "timeout",
            Self::MaxTotalTokens => "max_total_tokens",
            Self::OutputTruncated => "output_truncated",
            Self::ContextExhausted => "context_exhausted",
            Self::RetriesExhausted => "retries_exhausted",
            Self::ToolErrorsExhausted => "tool_errors_exhausted",
            Self::Cancelled => "cancelled",
            Self::ProviderError => "provider_error",
            Self::Refused => "refused",
        }
    }
}

impl core::fmt::Display for LabletRunStopReason {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        f.write_str(self.as_str())
    }
}

/// Where a tool comes from.
///
/// The values of `lablet.tool.source`.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum LabletToolSource {
    /// One of lablet's built-in tools.
    Builtin,
    /// A tool served by a configured MCP server.
    Mcp,
}

impl LabletToolSource {
    /// The value as it appears on the wire.
    #[must_use]
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::Builtin => "builtin",
            Self::Mcp => "mcp",
        }
    }
}

impl core::fmt::Display for LabletToolSource {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        f.write_str(self.as_str())
    }
}

/// How a tool call ended.
///
/// The values of `lablet.tool.status`.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum LabletToolStatus {
    /// The tool ran and returned a result.
    Ok,
    /// The tool ran and reported an error in its own result.
    ToolError,
    /// No configured tool has the name the model called.
    Unknown,
    /// The model's arguments for the call weren't valid JSON, so nothing ran.
    MalformedInput,
    /// The call ran past the tool timeout.
    Timeout,
    /// The executor failed before the tool could answer.
    Failed,
}

impl LabletToolStatus {
    /// The value as it appears on the wire.
    #[must_use]
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::Ok => "ok",
            Self::ToolError => "tool_error",
            Self::Unknown => "unknown",
            Self::MalformedInput => "malformed_input",
            Self::Timeout => "timeout",
            Self::Failed => "failed",
        }
    }
}

impl core::fmt::Display for LabletToolStatus {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        f.write_str(self.as_str())
    }
}
