// Generated by `cargo xtask weaver generate` from lablet/telemetry/registry/; don't edit.

//! The closed value sets: one enum for each lablet attribute whose type is a
//! list of members.

/// What a provider call is for.
///
/// The values of `lablet.chat.purpose`.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum LabletChatPurpose {
    /// The call asks the model for the next turn of the conversation.
    Turn,
}

impl LabletChatPurpose {
    /// Every value, each once, in the order the registry lists them.
    pub const ALL: [Self; 1] = [Self::Turn];

    /// The value as it appears on the wire.
    #[must_use]
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::Turn => "turn",
        }
    }
}

impl core::fmt::Display for LabletChatPurpose {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        f.write_str(self.as_str())
    }
}

/// How long the run's MCP servers live.
///
/// The values of `lablet.mcp.lifetime`.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum LabletMcpLifetime {
    /// The servers are started again for each run.
    Run,
    /// The servers are started once and serve every run of their `Lablet`.
    Lablet,
}

impl LabletMcpLifetime {
    /// Every value, each once, in the order the registry lists them.
    pub const ALL: [Self; 2] = [Self::Run, Self::Lablet];

    /// The value as it appears on the wire.
    #[must_use]
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::Run => "run",
            Self::Lablet => "lablet",
        }
    }
}

impl core::fmt::Display for LabletMcpLifetime {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        f.write_str(self.as_str())
    }
}

/// The API the run reached its model through.
///
/// The values of `lablet.request.api`.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum LabletRequestApi {
    /// Anthropic's Messages API.
    Messages,
    /// OpenAI's Responses API.
    Responses,
    /// OpenAI's chat completions, and every server that speaks them.
    ChatCompletions,
    /// The scripted provider's script.
    Script,
}

impl LabletRequestApi {
    /// Every value, each once, in the order the registry lists them.
    pub const ALL: [Self; 4] = [
        Self::Messages,
        Self::Responses,
        Self::ChatCompletions,
        Self::Script,
    ];

    /// The value as it appears on the wire.
    #[must_use]
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::Messages => "messages",
            Self::Responses => "responses",
            Self::ChatCompletions => "chat_completions",
            Self::Script => "script",
        }
    }
}

impl core::fmt::Display for LabletRequestApi {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        f.write_str(self.as_str())
    }
}

/// Which runs share what the provider caches of the run's requests.
///
/// The values of `lablet.request.cache_scope`.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum LabletRequestCacheScope {
    /// Every run that sends the same prefix shares what the provider caches of it.
    Shared,
    /// Each request carries the run id as its cache key, so no other run reads what this one cached.
    Run,
}

impl LabletRequestCacheScope {
    /// Every value, each once, in the order the registry lists them.
    pub const ALL: [Self; 2] = [Self::Shared, Self::Run];

    /// The value as it appears on the wire.
    #[must_use]
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::Shared => "shared",
            Self::Run => "run",
        }
    }
}

impl core::fmt::Display for LabletRequestCacheScope {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        f.write_str(self.as_str())
    }
}

/// How the run decides that the model has finished.
///
/// The values of `lablet.run.completion_mode`.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum LabletRunCompletionMode {
    /// The run completes when the model returns a turn with no tool calls.
    Natural,
    /// The run completes when the model calls `task_complete`.
    Explicit,
}

impl LabletRunCompletionMode {
    /// Every value, each once, in the order the registry lists them.
    pub const ALL: [Self; 2] = [Self::Natural, Self::Explicit];

    /// The value as it appears on the wire.
    #[must_use]
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::Natural => "natural",
            Self::Explicit => "explicit",
        }
    }
}

impl core::fmt::Display for LabletRunCompletionMode {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        f.write_str(self.as_str())
    }
}

/// Why the run ended.
///
/// The values of `lablet.run.stop_reason`.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum LabletRunStopReason {
    /// The model finished, by a turn with no tool calls or by calling `task_complete`.
    Completed,
    /// In explicit mode, the model returned a turn with no tool calls and never called `task_complete`.
    EndedWithoutCompletion,
    /// The run reached `run.max_turns`.
    MaxTurns,
    /// The run reached `run.timeout`.
    Timeout,
    /// Input plus output tokens reached `run.max_total_tokens`.
    MaxTotalTokens,
    /// The last response hit the output token limit. Its tool calls, if any, weren't executed.
    OutputTruncated,
    /// The conversation outgrew the model's context. The provider rejected the request as too long, or cut the response short at the window.
    ContextExhausted,
    /// One provider call failed on every attempt `run.max_retries` allows.
    RetriesExhausted,
    /// `run.max_consecutive_invalid_turns` turns in a row made no call that reached a tool.
    InvalidCallsExhausted,
    /// The run was cancelled.
    Cancelled,
    /// The provider returned an error that isn't retryable.
    ProviderError,
    /// The model declined to answer, or a content filter withheld the response.
    Refused,
}

impl LabletRunStopReason {
    /// Every value, each once, in the order the registry lists them.
    pub const ALL: [Self; 12] = [
        Self::Completed,
        Self::EndedWithoutCompletion,
        Self::MaxTurns,
        Self::Timeout,
        Self::MaxTotalTokens,
        Self::OutputTruncated,
        Self::ContextExhausted,
        Self::RetriesExhausted,
        Self::InvalidCallsExhausted,
        Self::Cancelled,
        Self::ProviderError,
        Self::Refused,
    ];

    /// The value as it appears on the wire.
    #[must_use]
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::Completed => "completed",
            Self::EndedWithoutCompletion => "ended_without_completion",
            Self::MaxTurns => "max_turns",
            Self::Timeout => "timeout",
            Self::MaxTotalTokens => "max_total_tokens",
            Self::OutputTruncated => "output_truncated",
            Self::ContextExhausted => "context_exhausted",
            Self::RetriesExhausted => "retries_exhausted",
            Self::InvalidCallsExhausted => "invalid_calls_exhausted",
            Self::Cancelled => "cancelled",
            Self::ProviderError => "provider_error",
            Self::Refused => "refused",
        }
    }
}

impl core::fmt::Display for LabletRunStopReason {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        f.write_str(self.as_str())
    }
}

/// Where a tool comes from.
///
/// The values of `lablet.tool.source`.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum LabletToolSource {
    /// One of lablet's built-in tools.
    Builtin,
    /// A tool served by a configured MCP server.
    Mcp,
}

impl LabletToolSource {
    /// Every value, each once, in the order the registry lists them.
    pub const ALL: [Self; 2] = [Self::Builtin, Self::Mcp];

    /// The value as it appears on the wire.
    #[must_use]
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::Builtin => "builtin",
            Self::Mcp => "mcp",
        }
    }
}

impl core::fmt::Display for LabletToolSource {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        f.write_str(self.as_str())
    }
}

/// How a tool call ended.
///
/// The values of `lablet.tool.status`.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum LabletToolStatus {
    /// The tool ran and returned a result.
    Ok,
    /// The tool ran and reported an error in its own result.
    ToolError,
    /// No configured tool has the name the model called.
    Unknown,
    /// The model's arguments for the call weren't valid JSON, so nothing ran.
    MalformedInput,
    /// The loop declined a `task_complete` call that wasn't the response's only call, so nothing ran.
    Rejected,
    /// The call's turn came when the run had no time left, so nothing was started for it. No span carries it.
    NotRun,
    /// The call ran past its deadline, the shorter of its executor's own limit and the time the run had left.
    Timeout,
    /// The executor failed before the tool could answer.
    Failed,
}

impl LabletToolStatus {
    /// Every value, each once, in the order the registry lists them.
    pub const ALL: [Self; 8] = [
        Self::Ok,
        Self::ToolError,
        Self::Unknown,
        Self::MalformedInput,
        Self::Rejected,
        Self::NotRun,
        Self::Timeout,
        Self::Failed,
    ];

    /// The value as it appears on the wire.
    #[must_use]
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::Ok => "ok",
            Self::ToolError => "tool_error",
            Self::Unknown => "unknown",
            Self::MalformedInput => "malformed_input",
            Self::Rejected => "rejected",
            Self::NotRun => "not_run",
            Self::Timeout => "timeout",
            Self::Failed => "failed",
        }
    }
}

impl core::fmt::Display for LabletToolStatus {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        f.write_str(self.as_str())
    }
}
