// Generated by `cargo xtask weaver generate` from lablet/telemetry/registry/; don't edit.

//! The attribute keys of each span and event, for tests that hold an emitted
//! signal to the registry, and the keys of the wide event as enums, for what
//! fills it. A template attribute is listed by its prefix.

use crate::attribute;

/// Keys span `lablet.chat` always carries. It's of kind `client`, named `chat {gen_ai.request.model}`.
pub const SPAN_LABLET_CHAT_REQUIRED: &[&str] = &[
    attribute::GEN_AI_CONVERSATION_ID,
    attribute::GEN_AI_OPERATION_NAME,
    attribute::GEN_AI_PROVIDER_NAME,
    attribute::GEN_AI_REQUEST_MAX_TOKENS,
    attribute::GEN_AI_REQUEST_MODEL,
    attribute::LABLET_ATTEMPT,
    attribute::LABLET_CHAT_PURPOSE,
    attribute::LABLET_CONFIG_DIGEST,
    attribute::LABLET_REQUEST_BYTES,
    attribute::LABLET_TURN,
    attribute::SESSION_ID,
];

/// Every key span `lablet.chat` may carry.
pub const SPAN_LABLET_CHAT_KEYS: &[&str] = &[
    attribute::ERROR_TYPE,
    attribute::GEN_AI_CONVERSATION_ID,
    attribute::GEN_AI_OPERATION_NAME,
    attribute::GEN_AI_PROVIDER_NAME,
    attribute::GEN_AI_REQUEST_MAX_TOKENS,
    attribute::GEN_AI_REQUEST_MODEL,
    attribute::GEN_AI_REQUEST_REASONING_LEVEL,
    attribute::GEN_AI_REQUEST_SEED,
    attribute::GEN_AI_REQUEST_TEMPERATURE,
    attribute::GEN_AI_RESPONSE_FINISH_REASONS,
    attribute::GEN_AI_RESPONSE_ID,
    attribute::GEN_AI_RESPONSE_MODEL,
    attribute::GEN_AI_USAGE_CACHE_READ_INPUT_TOKENS,
    attribute::GEN_AI_USAGE_CACHE_WRITE_INPUT_TOKENS,
    attribute::GEN_AI_USAGE_INPUT_TOKENS,
    attribute::GEN_AI_USAGE_OUTPUT_TOKENS,
    attribute::GEN_AI_USAGE_REASONING_OUTPUT_TOKENS,
    attribute::LABLET_ATTEMPT,
    attribute::LABLET_CHAT_PURPOSE,
    attribute::LABLET_CONFIG_DIGEST,
    attribute::LABLET_EXPERIMENT_ID,
    attribute::LABLET_REQUEST_BYTES,
    attribute::LABLET_TASK_ID,
    attribute::LABLET_TRIAL,
    attribute::LABLET_TURN,
    attribute::SERVER_ADDRESS,
    attribute::SERVER_PORT,
    attribute::SESSION_ID,
];

/// Keys span `lablet.execute_tool` always carries. It's of kind `internal`, named `execute_tool {gen_ai.tool.name}`.
pub const SPAN_LABLET_EXECUTE_TOOL_REQUIRED: &[&str] = &[
    attribute::GEN_AI_CONVERSATION_ID,
    attribute::GEN_AI_OPERATION_NAME,
    attribute::GEN_AI_TOOL_CALL_ID,
    attribute::GEN_AI_TOOL_NAME,
    attribute::LABLET_CONFIG_DIGEST,
    attribute::LABLET_TOOL_INPUT_BYTES,
    attribute::LABLET_TOOL_IS_ERROR,
    attribute::LABLET_TOOL_OUTPUT_BYTES,
    attribute::LABLET_TOOL_OUTPUT_TRUNCATED,
    attribute::LABLET_TOOL_STATUS,
    attribute::LABLET_TURN,
    attribute::SESSION_ID,
];

/// Every key span `lablet.execute_tool` may carry.
pub const SPAN_LABLET_EXECUTE_TOOL_KEYS: &[&str] = &[
    attribute::ERROR_TYPE,
    attribute::GEN_AI_CONVERSATION_ID,
    attribute::GEN_AI_OPERATION_NAME,
    attribute::GEN_AI_TOOL_CALL_ID,
    attribute::GEN_AI_TOOL_DESCRIPTION,
    attribute::GEN_AI_TOOL_NAME,
    attribute::GEN_AI_TOOL_TYPE,
    attribute::JSONRPC_REQUEST_ID,
    attribute::LABLET_CONFIG_DIGEST,
    attribute::LABLET_EXPERIMENT_ID,
    attribute::LABLET_TASK_ID,
    attribute::LABLET_TOOL_INPUT_BYTES,
    attribute::LABLET_TOOL_IS_ERROR,
    attribute::LABLET_TOOL_OUTPUT_BYTES,
    attribute::LABLET_TOOL_OUTPUT_ORIGINAL_BYTES,
    attribute::LABLET_TOOL_OUTPUT_TRUNCATED,
    attribute::LABLET_TOOL_SOURCE,
    attribute::LABLET_TOOL_STATUS,
    attribute::LABLET_TRIAL,
    attribute::LABLET_TURN,
    attribute::MCP_METHOD_NAME,
    attribute::MCP_PROTOCOL_VERSION,
    attribute::MCP_SESSION_ID,
    attribute::NETWORK_TRANSPORT,
    attribute::RPC_RESPONSE_STATUS_CODE,
    attribute::SESSION_ID,
];

/// Keys span `lablet.invoke_agent` always carries. It's of kind `internal`, named `invoke_agent {gen_ai.agent.name}`.
pub const SPAN_LABLET_INVOKE_AGENT_REQUIRED: &[&str] = &[
    attribute::GEN_AI_AGENT_NAME,
    attribute::GEN_AI_AGENT_VERSION,
    attribute::GEN_AI_CONVERSATION_ID,
    attribute::GEN_AI_OPERATION_NAME,
    attribute::GEN_AI_REQUEST_MODEL,
    attribute::GEN_AI_USAGE_INPUT_TOKENS,
    attribute::GEN_AI_USAGE_OUTPUT_TOKENS,
    attribute::LABLET_CONFIG_DIGEST,
    attribute::LABLET_RUN_STOP_REASON,
    attribute::LABLET_RUN_TURNS,
    attribute::LABLET_TOOL_CALLS_TOTAL,
    attribute::SESSION_ID,
];

/// Every key span `lablet.invoke_agent` may carry.
pub const SPAN_LABLET_INVOKE_AGENT_KEYS: &[&str] = &[
    attribute::ERROR_TYPE,
    attribute::GEN_AI_AGENT_NAME,
    attribute::GEN_AI_AGENT_VERSION,
    attribute::GEN_AI_CONVERSATION_ID,
    attribute::GEN_AI_OPERATION_NAME,
    attribute::GEN_AI_REQUEST_MODEL,
    attribute::GEN_AI_USAGE_CACHE_READ_INPUT_TOKENS,
    attribute::GEN_AI_USAGE_CACHE_WRITE_INPUT_TOKENS,
    attribute::GEN_AI_USAGE_INPUT_TOKENS,
    attribute::GEN_AI_USAGE_OUTPUT_TOKENS,
    attribute::GEN_AI_USAGE_REASONING_OUTPUT_TOKENS,
    attribute::LABLET_CONFIG_DIGEST,
    attribute::LABLET_EXPERIMENT_ID,
    attribute::LABLET_RUN_COST_USD,
    attribute::LABLET_RUN_STOP_REASON,
    attribute::LABLET_RUN_TURNS,
    attribute::LABLET_TASK_ID,
    attribute::LABLET_TOOL_CALLS_TOTAL,
    attribute::LABLET_TRIAL,
    attribute::SESSION_ID,
];

/// Name of event `gen_ai.client.inference.operation.details`.
pub const EVENT_GEN_AI_CLIENT_INFERENCE_OPERATION_DETAILS_NAME: &str =
    "gen_ai.client.inference.operation.details";

/// Keys event `gen_ai.client.inference.operation.details` always carries.
pub const EVENT_GEN_AI_CLIENT_INFERENCE_OPERATION_DETAILS_REQUIRED: &[&str] = &[
    attribute::GEN_AI_CONVERSATION_ID,
    attribute::GEN_AI_OPERATION_NAME,
    attribute::LABLET_CONFIG_DIGEST,
    attribute::SESSION_ID,
];

/// Every key event `gen_ai.client.inference.operation.details` may carry.
pub const EVENT_GEN_AI_CLIENT_INFERENCE_OPERATION_DETAILS_KEYS: &[&str] = &[
    attribute::GEN_AI_CONVERSATION_ID,
    attribute::GEN_AI_INPUT_MESSAGES,
    attribute::GEN_AI_OPERATION_NAME,
    attribute::GEN_AI_OUTPUT_MESSAGES,
    attribute::GEN_AI_SYSTEM_INSTRUCTIONS,
    attribute::GEN_AI_TOOL_CALL_ARGUMENTS,
    attribute::GEN_AI_TOOL_CALL_ID,
    attribute::GEN_AI_TOOL_CALL_RESULT,
    attribute::GEN_AI_TOOL_DEFINITIONS,
    attribute::GEN_AI_TOOL_NAME,
    attribute::LABLET_CONFIG_DIGEST,
    attribute::LABLET_EXPERIMENT_ID,
    attribute::LABLET_TASK_ID,
    attribute::LABLET_TRIAL,
    attribute::LABLET_TURN,
    attribute::SESSION_ID,
];

/// Name of event `gen_ai.client.operation.exception`.
pub const EVENT_GEN_AI_CLIENT_OPERATION_EXCEPTION_NAME: &str = "gen_ai.client.operation.exception";

/// Keys event `gen_ai.client.operation.exception` always carries.
pub const EVENT_GEN_AI_CLIENT_OPERATION_EXCEPTION_REQUIRED: &[&str] = &[
    attribute::EXCEPTION_MESSAGE,
    attribute::EXCEPTION_TYPE,
    attribute::GEN_AI_CONVERSATION_ID,
    attribute::GEN_AI_OPERATION_NAME,
    attribute::GEN_AI_PROVIDER_NAME,
    attribute::GEN_AI_REQUEST_MODEL,
    attribute::LABLET_ATTEMPT,
    attribute::LABLET_CONFIG_DIGEST,
    attribute::LABLET_TURN,
    attribute::SESSION_ID,
];

/// Every key event `gen_ai.client.operation.exception` may carry.
pub const EVENT_GEN_AI_CLIENT_OPERATION_EXCEPTION_KEYS: &[&str] = &[
    attribute::EXCEPTION_MESSAGE,
    attribute::EXCEPTION_TYPE,
    attribute::GEN_AI_CONVERSATION_ID,
    attribute::GEN_AI_OPERATION_NAME,
    attribute::GEN_AI_PROVIDER_NAME,
    attribute::GEN_AI_REQUEST_MODEL,
    attribute::LABLET_ATTEMPT,
    attribute::LABLET_CONFIG_DIGEST,
    attribute::LABLET_EXPERIMENT_ID,
    attribute::LABLET_TASK_ID,
    attribute::LABLET_TRIAL,
    attribute::LABLET_TURN,
    attribute::SESSION_ID,
];

/// Name of event `lablet.retry`.
pub const EVENT_LABLET_RETRY_NAME: &str = "lablet.retry";

/// Keys event `lablet.retry` always carries.
pub const EVENT_LABLET_RETRY_REQUIRED: &[&str] = &[
    attribute::LABLET_ATTEMPT,
    attribute::LABLET_RETRY_WILL_RETRY,
];

/// Every key event `lablet.retry` may carry.
pub const EVENT_LABLET_RETRY_KEYS: &[&str] = &[
    attribute::LABLET_ATTEMPT,
    attribute::LABLET_RETRY_BACKOFF_MS,
    attribute::LABLET_RETRY_WILL_RETRY,
];

/// Name of event `lablet.run`.
pub const EVENT_LABLET_RUN_NAME: &str = "lablet.run";

/// Keys event `lablet.run` always carries.
pub const EVENT_LABLET_RUN_REQUIRED: &[&str] = &[
    attribute::GEN_AI_AGENT_NAME,
    attribute::GEN_AI_AGENT_VERSION,
    attribute::GEN_AI_CONVERSATION_ID,
    attribute::GEN_AI_PROVIDER_NAME,
    attribute::GEN_AI_REQUEST_MAX_TOKENS,
    attribute::GEN_AI_REQUEST_MODEL,
    attribute::GEN_AI_RESPONSE_FINISH_REASONS,
    attribute::GEN_AI_USAGE_INPUT_TOKENS,
    attribute::GEN_AI_USAGE_OUTPUT_TOKENS,
    attribute::LABLET_CONFIG_DIGEST,
    attribute::LABLET_PROMPT_SYSTEM_BYTES,
    attribute::LABLET_PROMPT_SYSTEM_DIGEST,
    attribute::LABLET_PROMPT_TOOLS_BYTES,
    attribute::LABLET_PROMPT_USER_BYTES,
    attribute::LABLET_PROVIDER_LATENCY_MS_MAX,
    attribute::LABLET_PROVIDER_LATENCY_MS_TOTAL,
    attribute::LABLET_PROVIDER_RETRIES,
    attribute::LABLET_REQUEST_API,
    attribute::LABLET_REQUEST_CACHE_SCOPE,
    attribute::LABLET_REQUEST_REASONING_REPLAYED,
    attribute::LABLET_REQUEST_THINKING,
    attribute::LABLET_RESULT_HAS_STRUCTURED,
    attribute::LABLET_RESULT_TEXT_BYTES,
    attribute::LABLET_RUN_COMPLETION_MODE,
    attribute::LABLET_RUN_DURATION_MS,
    attribute::LABLET_RUN_STOP_REASON,
    attribute::LABLET_RUN_TIMEOUT_MS,
    attribute::LABLET_RUN_TURNS,
    attribute::LABLET_SKILLS_COUNT,
    attribute::LABLET_TELEMETRY_DROPPED_RECORDS,
    attribute::LABLET_TOOL_CALLS_ERRORS,
    attribute::LABLET_TOOL_CALLS_INPUT_BYTES_TOTAL,
    attribute::LABLET_TOOL_CALLS_LATENCY_MS_TOTAL,
    attribute::LABLET_TOOL_CALLS_OUTPUT_BYTES_TOTAL,
    attribute::LABLET_TOOL_CALLS_TOTAL,
    attribute::LABLET_TOOL_CALLS_TRUNCATED,
    attribute::LABLET_TOOL_CALLS_UNKNOWN,
    attribute::LABLET_TOOLS_COUNT,
    attribute::LABLET_TOOLS_DIGEST,
    attribute::LABLET_TOOLS_NAMES,
    attribute::SESSION_ID,
];

/// Every key event `lablet.run` may carry.
pub const EVENT_LABLET_RUN_KEYS: &[&str] = &[
    attribute::ERROR_TYPE,
    attribute::GEN_AI_AGENT_NAME,
    attribute::GEN_AI_AGENT_VERSION,
    attribute::GEN_AI_CONVERSATION_ID,
    attribute::GEN_AI_PROVIDER_NAME,
    attribute::GEN_AI_REQUEST_MAX_TOKENS,
    attribute::GEN_AI_REQUEST_MODEL,
    attribute::GEN_AI_REQUEST_REASONING_LEVEL,
    attribute::GEN_AI_REQUEST_SEED,
    attribute::GEN_AI_REQUEST_TEMPERATURE,
    attribute::GEN_AI_RESPONSE_FINISH_REASONS,
    attribute::GEN_AI_USAGE_CACHE_READ_INPUT_TOKENS,
    attribute::GEN_AI_USAGE_CACHE_WRITE_INPUT_TOKENS,
    attribute::GEN_AI_USAGE_INPUT_TOKENS,
    attribute::GEN_AI_USAGE_OUTPUT_TOKENS,
    attribute::GEN_AI_USAGE_REASONING_OUTPUT_TOKENS,
    attribute::LABLET_CONFIG_DIGEST,
    attribute::LABLET_EXPERIMENT_ID,
    attribute::LABLET_MCP_LIFETIME,
    attribute::LABLET_MCP_SERVER_VERSIONS,
    attribute::LABLET_MCP_SERVERS,
    attribute::LABLET_PRICING_CACHE_READ_USD_PER_MTOK,
    attribute::LABLET_PRICING_CACHE_WRITE_USD_PER_MTOK,
    attribute::LABLET_PRICING_INPUT_USD_PER_MTOK,
    attribute::LABLET_PRICING_OUTPUT_USD_PER_MTOK,
    attribute::LABLET_PROMPT_SYSTEM_BYTES,
    attribute::LABLET_PROMPT_SYSTEM_DIGEST,
    attribute::LABLET_PROMPT_TOOLS_BYTES,
    attribute::LABLET_PROMPT_USER_BYTES,
    attribute::LABLET_PROVIDER_FAILED_CACHE_READ_INPUT_TOKENS,
    attribute::LABLET_PROVIDER_FAILED_CACHE_WRITE_INPUT_TOKENS,
    attribute::LABLET_PROVIDER_FAILED_INPUT_TOKENS,
    attribute::LABLET_PROVIDER_FAILED_OUTPUT_TOKENS,
    attribute::LABLET_PROVIDER_LATENCY_MS_MAX,
    attribute::LABLET_PROVIDER_LATENCY_MS_TOTAL,
    attribute::LABLET_PROVIDER_RETRIES,
    attribute::LABLET_REQUEST_API,
    attribute::LABLET_REQUEST_CACHE_SCOPE,
    attribute::LABLET_REQUEST_REASONING_REPLAYED,
    attribute::LABLET_REQUEST_THINKING,
    attribute::LABLET_RESULT_HAS_STRUCTURED,
    attribute::LABLET_RESULT_STRUCTURED,
    attribute::LABLET_RESULT_TEXT,
    attribute::LABLET_RESULT_TEXT_BYTES,
    attribute::LABLET_RUN_COMPLETION_MODE,
    attribute::LABLET_RUN_COST_USD,
    attribute::LABLET_RUN_DURATION_MS,
    attribute::LABLET_RUN_ERROR,
    attribute::LABLET_RUN_MAX_TURNS,
    attribute::LABLET_RUN_STOP_REASON,
    attribute::LABLET_RUN_TIMEOUT_MS,
    attribute::LABLET_RUN_TRANSCRIPT_PATH,
    attribute::LABLET_RUN_TURNS,
    attribute::LABLET_SKILLS_COUNT,
    attribute::LABLET_TASK_ID,
    attribute::LABLET_TELEMETRY_DROPPED_RECORDS,
    attribute::LABLET_TOOL_CALLS,
    attribute::LABLET_TOOL_ERRORS,
    attribute::LABLET_TOOL_LATENCY_MS,
    attribute::LABLET_TOOL_CALLS_ERRORS,
    attribute::LABLET_TOOL_CALLS_INPUT_BYTES_TOTAL,
    attribute::LABLET_TOOL_CALLS_LATENCY_MS_TOTAL,
    attribute::LABLET_TOOL_CALLS_OUTPUT_BYTES_TOTAL,
    attribute::LABLET_TOOL_CALLS_TOTAL,
    attribute::LABLET_TOOL_CALLS_TRUNCATED,
    attribute::LABLET_TOOL_CALLS_UNKNOWN,
    attribute::LABLET_TOOLS_COUNT,
    attribute::LABLET_TOOLS_DIGEST,
    attribute::LABLET_TOOLS_NAMES,
    attribute::LABLET_TRIAL,
    attribute::SERVER_ADDRESS,
    attribute::SERVER_PORT,
    attribute::SESSION_ID,
];

/// The keys of event `lablet.run` that aren't templates, one variant for
/// each.
///
/// What fills the event matches on these with no wildcard arm, and takes
/// each key's name from its variant. So a key the registry gains doesn't
/// compile until the match says what the key holds, and no key is filled
/// twice or under another's name.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum EventLabletRunKey {
    /// `error.type`. Conditionally required: If the stop reason isn't `completed`.
    ErrorType,
    /// `gen_ai.agent.name`. Required.
    GenAiAgentName,
    /// `gen_ai.agent.version`. Required.
    GenAiAgentVersion,
    /// `gen_ai.conversation.id`. Required.
    GenAiConversationId,
    /// `gen_ai.provider.name`. Required.
    GenAiProviderName,
    /// `gen_ai.request.max_tokens`. Required.
    GenAiRequestMaxTokens,
    /// `gen_ai.request.model`. Required.
    GenAiRequestModel,
    /// `gen_ai.request.reasoning.level`. Conditionally required: If `model.effort` is set.
    GenAiRequestReasoningLevel,
    /// `gen_ai.request.seed`. Conditionally required: If `model.seed` is set.
    GenAiRequestSeed,
    /// `gen_ai.request.temperature`. Conditionally required: If `model.temperature` is set.
    GenAiRequestTemperature,
    /// `gen_ai.response.finish_reasons`. Required.
    GenAiResponseFinishReasons,
    /// `gen_ai.usage.cache_read.input_tokens`. Conditionally required: If a successful provider call reported the count.
    GenAiUsageCacheReadInputTokens,
    /// `gen_ai.usage.cache_write.input_tokens`. Conditionally required: If a successful provider call reported the count.
    GenAiUsageCacheWriteInputTokens,
    /// `gen_ai.usage.input_tokens`. Required.
    GenAiUsageInputTokens,
    /// `gen_ai.usage.output_tokens`. Required.
    GenAiUsageOutputTokens,
    /// `gen_ai.usage.reasoning.output_tokens`. Conditionally required: If a successful provider call reported the count.
    GenAiUsageReasoningOutputTokens,
    /// `lablet.config.digest`. Required.
    LabletConfigDigest,
    /// `lablet.experiment.id`. Conditionally required: If the run request named an experiment.
    LabletExperimentId,
    /// `lablet.mcp.lifetime`. Conditionally required: If the run has MCP servers.
    LabletMcpLifetime,
    /// `lablet.mcp.server_versions`. Conditionally required: If the run has MCP servers.
    LabletMcpServerVersions,
    /// `lablet.mcp.servers`. Conditionally required: If the run has MCP servers.
    LabletMcpServers,
    /// `lablet.pricing.cache_read_usd_per_mtok`. Conditionally required: If `model.pricing` is configured.
    LabletPricingCacheReadUsdPerMtok,
    /// `lablet.pricing.cache_write_usd_per_mtok`. Conditionally required: If `model.pricing` is configured.
    LabletPricingCacheWriteUsdPerMtok,
    /// `lablet.pricing.input_usd_per_mtok`. Conditionally required: If `model.pricing` is configured.
    LabletPricingInputUsdPerMtok,
    /// `lablet.pricing.output_usd_per_mtok`. Conditionally required: If `model.pricing` is configured.
    LabletPricingOutputUsdPerMtok,
    /// `lablet.prompt.system_bytes`. Required.
    LabletPromptSystemBytes,
    /// `lablet.prompt.system_digest`. Required.
    LabletPromptSystemDigest,
    /// `lablet.prompt.tools_bytes`. Required.
    LabletPromptToolsBytes,
    /// `lablet.prompt.user_bytes`. Required.
    LabletPromptUserBytes,
    /// `lablet.provider.failed.cache_read.input_tokens`. Conditionally required: If a failed provider call attempt reported the count.
    LabletProviderFailedCacheReadInputTokens,
    /// `lablet.provider.failed.cache_write.input_tokens`. Conditionally required: If a failed provider call attempt reported the count.
    LabletProviderFailedCacheWriteInputTokens,
    /// `lablet.provider.failed.input_tokens`. Conditionally required: If a failed provider call attempt reported what it used.
    LabletProviderFailedInputTokens,
    /// `lablet.provider.failed.output_tokens`. Conditionally required: If a failed provider call attempt reported what it used.
    LabletProviderFailedOutputTokens,
    /// `lablet.provider.latency_ms.max`. Required.
    LabletProviderLatencyMsMax,
    /// `lablet.provider.latency_ms.total`. Required.
    LabletProviderLatencyMsTotal,
    /// `lablet.provider.retries`. Required.
    LabletProviderRetries,
    /// `lablet.request.api`. Required.
    LabletRequestApi,
    /// `lablet.request.cache_scope`. Required.
    LabletRequestCacheScope,
    /// `lablet.request.reasoning_replayed`. Required.
    LabletRequestReasoningReplayed,
    /// `lablet.request.thinking`. Required.
    LabletRequestThinking,
    /// `lablet.result.has_structured`. Required.
    LabletResultHasStructured,
    /// `lablet.result.structured`. Opt-in.
    LabletResultStructured,
    /// `lablet.result.text`. Opt-in.
    LabletResultText,
    /// `lablet.result.text_bytes`. Required.
    LabletResultTextBytes,
    /// `lablet.run.completion_mode`. Required.
    LabletRunCompletionMode,
    /// `lablet.run.cost_usd`. Conditionally required: If `model.pricing` is configured.
    LabletRunCostUsd,
    /// `lablet.run.duration_ms`. Required.
    LabletRunDurationMs,
    /// `lablet.run.error`. Conditionally required: If an error ended the run.
    LabletRunError,
    /// `lablet.run.max_turns`. Conditionally required: If `run.max_turns` is set.
    LabletRunMaxTurns,
    /// `lablet.run.stop_reason`. Required.
    LabletRunStopReason,
    /// `lablet.run.timeout_ms`. Required.
    LabletRunTimeoutMs,
    /// `lablet.run.transcript_path`. Conditionally required: If `run.transcript_path` is set.
    LabletRunTranscriptPath,
    /// `lablet.run.turns`. Required.
    LabletRunTurns,
    /// `lablet.skills.count`. Required.
    LabletSkillsCount,
    /// `lablet.task.id`. Conditionally required: If the run request named a task.
    LabletTaskId,
    /// `lablet.telemetry.dropped_records`. Required.
    LabletTelemetryDroppedRecords,
    /// `lablet.tool_calls.errors`. Required.
    LabletToolCallsErrors,
    /// `lablet.tool_calls.input_bytes.total`. Required.
    LabletToolCallsInputBytesTotal,
    /// `lablet.tool_calls.latency_ms.total`. Required.
    LabletToolCallsLatencyMsTotal,
    /// `lablet.tool_calls.output_bytes.total`. Required.
    LabletToolCallsOutputBytesTotal,
    /// `lablet.tool_calls.total`. Required.
    LabletToolCallsTotal,
    /// `lablet.tool_calls.truncated`. Required.
    LabletToolCallsTruncated,
    /// `lablet.tool_calls.unknown`. Required.
    LabletToolCallsUnknown,
    /// `lablet.tools.count`. Required.
    LabletToolsCount,
    /// `lablet.tools.digest`. Required.
    LabletToolsDigest,
    /// `lablet.tools.names`. Required.
    LabletToolsNames,
    /// `lablet.trial`. Conditionally required: If the run request named a trial.
    LabletTrial,
    /// `server.address`. Conditionally required: If the provider is reached over the network.
    ServerAddress,
    /// `server.port`. Conditionally required: If `server.address` is set.
    ServerPort,
    /// `session.id`. Required.
    SessionId,
}

impl EventLabletRunKey {
    /// Every key, each once.
    pub const ALL: &[Self] = &[
        Self::ErrorType,
        Self::GenAiAgentName,
        Self::GenAiAgentVersion,
        Self::GenAiConversationId,
        Self::GenAiProviderName,
        Self::GenAiRequestMaxTokens,
        Self::GenAiRequestModel,
        Self::GenAiRequestReasoningLevel,
        Self::GenAiRequestSeed,
        Self::GenAiRequestTemperature,
        Self::GenAiResponseFinishReasons,
        Self::GenAiUsageCacheReadInputTokens,
        Self::GenAiUsageCacheWriteInputTokens,
        Self::GenAiUsageInputTokens,
        Self::GenAiUsageOutputTokens,
        Self::GenAiUsageReasoningOutputTokens,
        Self::LabletConfigDigest,
        Self::LabletExperimentId,
        Self::LabletMcpLifetime,
        Self::LabletMcpServerVersions,
        Self::LabletMcpServers,
        Self::LabletPricingCacheReadUsdPerMtok,
        Self::LabletPricingCacheWriteUsdPerMtok,
        Self::LabletPricingInputUsdPerMtok,
        Self::LabletPricingOutputUsdPerMtok,
        Self::LabletPromptSystemBytes,
        Self::LabletPromptSystemDigest,
        Self::LabletPromptToolsBytes,
        Self::LabletPromptUserBytes,
        Self::LabletProviderFailedCacheReadInputTokens,
        Self::LabletProviderFailedCacheWriteInputTokens,
        Self::LabletProviderFailedInputTokens,
        Self::LabletProviderFailedOutputTokens,
        Self::LabletProviderLatencyMsMax,
        Self::LabletProviderLatencyMsTotal,
        Self::LabletProviderRetries,
        Self::LabletRequestApi,
        Self::LabletRequestCacheScope,
        Self::LabletRequestReasoningReplayed,
        Self::LabletRequestThinking,
        Self::LabletResultHasStructured,
        Self::LabletResultStructured,
        Self::LabletResultText,
        Self::LabletResultTextBytes,
        Self::LabletRunCompletionMode,
        Self::LabletRunCostUsd,
        Self::LabletRunDurationMs,
        Self::LabletRunError,
        Self::LabletRunMaxTurns,
        Self::LabletRunStopReason,
        Self::LabletRunTimeoutMs,
        Self::LabletRunTranscriptPath,
        Self::LabletRunTurns,
        Self::LabletSkillsCount,
        Self::LabletTaskId,
        Self::LabletTelemetryDroppedRecords,
        Self::LabletToolCallsErrors,
        Self::LabletToolCallsInputBytesTotal,
        Self::LabletToolCallsLatencyMsTotal,
        Self::LabletToolCallsOutputBytesTotal,
        Self::LabletToolCallsTotal,
        Self::LabletToolCallsTruncated,
        Self::LabletToolCallsUnknown,
        Self::LabletToolsCount,
        Self::LabletToolsDigest,
        Self::LabletToolsNames,
        Self::LabletTrial,
        Self::ServerAddress,
        Self::ServerPort,
        Self::SessionId,
    ];

    /// The attribute's name.
    #[must_use]
    pub const fn name(self) -> &'static str {
        match self {
            Self::ErrorType => attribute::ERROR_TYPE,
            Self::GenAiAgentName => attribute::GEN_AI_AGENT_NAME,
            Self::GenAiAgentVersion => attribute::GEN_AI_AGENT_VERSION,
            Self::GenAiConversationId => attribute::GEN_AI_CONVERSATION_ID,
            Self::GenAiProviderName => attribute::GEN_AI_PROVIDER_NAME,
            Self::GenAiRequestMaxTokens => attribute::GEN_AI_REQUEST_MAX_TOKENS,
            Self::GenAiRequestModel => attribute::GEN_AI_REQUEST_MODEL,
            Self::GenAiRequestReasoningLevel => attribute::GEN_AI_REQUEST_REASONING_LEVEL,
            Self::GenAiRequestSeed => attribute::GEN_AI_REQUEST_SEED,
            Self::GenAiRequestTemperature => attribute::GEN_AI_REQUEST_TEMPERATURE,
            Self::GenAiResponseFinishReasons => attribute::GEN_AI_RESPONSE_FINISH_REASONS,
            Self::GenAiUsageCacheReadInputTokens => attribute::GEN_AI_USAGE_CACHE_READ_INPUT_TOKENS,
            Self::GenAiUsageCacheWriteInputTokens => {
                attribute::GEN_AI_USAGE_CACHE_WRITE_INPUT_TOKENS
            }
            Self::GenAiUsageInputTokens => attribute::GEN_AI_USAGE_INPUT_TOKENS,
            Self::GenAiUsageOutputTokens => attribute::GEN_AI_USAGE_OUTPUT_TOKENS,
            Self::GenAiUsageReasoningOutputTokens => {
                attribute::GEN_AI_USAGE_REASONING_OUTPUT_TOKENS
            }
            Self::LabletConfigDigest => attribute::LABLET_CONFIG_DIGEST,
            Self::LabletExperimentId => attribute::LABLET_EXPERIMENT_ID,
            Self::LabletMcpLifetime => attribute::LABLET_MCP_LIFETIME,
            Self::LabletMcpServerVersions => attribute::LABLET_MCP_SERVER_VERSIONS,
            Self::LabletMcpServers => attribute::LABLET_MCP_SERVERS,
            Self::LabletPricingCacheReadUsdPerMtok => {
                attribute::LABLET_PRICING_CACHE_READ_USD_PER_MTOK
            }
            Self::LabletPricingCacheWriteUsdPerMtok => {
                attribute::LABLET_PRICING_CACHE_WRITE_USD_PER_MTOK
            }
            Self::LabletPricingInputUsdPerMtok => attribute::LABLET_PRICING_INPUT_USD_PER_MTOK,
            Self::LabletPricingOutputUsdPerMtok => attribute::LABLET_PRICING_OUTPUT_USD_PER_MTOK,
            Self::LabletPromptSystemBytes => attribute::LABLET_PROMPT_SYSTEM_BYTES,
            Self::LabletPromptSystemDigest => attribute::LABLET_PROMPT_SYSTEM_DIGEST,
            Self::LabletPromptToolsBytes => attribute::LABLET_PROMPT_TOOLS_BYTES,
            Self::LabletPromptUserBytes => attribute::LABLET_PROMPT_USER_BYTES,
            Self::LabletProviderFailedCacheReadInputTokens => {
                attribute::LABLET_PROVIDER_FAILED_CACHE_READ_INPUT_TOKENS
            }
            Self::LabletProviderFailedCacheWriteInputTokens => {
                attribute::LABLET_PROVIDER_FAILED_CACHE_WRITE_INPUT_TOKENS
            }
            Self::LabletProviderFailedInputTokens => attribute::LABLET_PROVIDER_FAILED_INPUT_TOKENS,
            Self::LabletProviderFailedOutputTokens => {
                attribute::LABLET_PROVIDER_FAILED_OUTPUT_TOKENS
            }
            Self::LabletProviderLatencyMsMax => attribute::LABLET_PROVIDER_LATENCY_MS_MAX,
            Self::LabletProviderLatencyMsTotal => attribute::LABLET_PROVIDER_LATENCY_MS_TOTAL,
            Self::LabletProviderRetries => attribute::LABLET_PROVIDER_RETRIES,
            Self::LabletRequestApi => attribute::LABLET_REQUEST_API,
            Self::LabletRequestCacheScope => attribute::LABLET_REQUEST_CACHE_SCOPE,
            Self::LabletRequestReasoningReplayed => attribute::LABLET_REQUEST_REASONING_REPLAYED,
            Self::LabletRequestThinking => attribute::LABLET_REQUEST_THINKING,
            Self::LabletResultHasStructured => attribute::LABLET_RESULT_HAS_STRUCTURED,
            Self::LabletResultStructured => attribute::LABLET_RESULT_STRUCTURED,
            Self::LabletResultText => attribute::LABLET_RESULT_TEXT,
            Self::LabletResultTextBytes => attribute::LABLET_RESULT_TEXT_BYTES,
            Self::LabletRunCompletionMode => attribute::LABLET_RUN_COMPLETION_MODE,
            Self::LabletRunCostUsd => attribute::LABLET_RUN_COST_USD,
            Self::LabletRunDurationMs => attribute::LABLET_RUN_DURATION_MS,
            Self::LabletRunError => attribute::LABLET_RUN_ERROR,
            Self::LabletRunMaxTurns => attribute::LABLET_RUN_MAX_TURNS,
            Self::LabletRunStopReason => attribute::LABLET_RUN_STOP_REASON,
            Self::LabletRunTimeoutMs => attribute::LABLET_RUN_TIMEOUT_MS,
            Self::LabletRunTranscriptPath => attribute::LABLET_RUN_TRANSCRIPT_PATH,
            Self::LabletRunTurns => attribute::LABLET_RUN_TURNS,
            Self::LabletSkillsCount => attribute::LABLET_SKILLS_COUNT,
            Self::LabletTaskId => attribute::LABLET_TASK_ID,
            Self::LabletTelemetryDroppedRecords => attribute::LABLET_TELEMETRY_DROPPED_RECORDS,
            Self::LabletToolCallsErrors => attribute::LABLET_TOOL_CALLS_ERRORS,
            Self::LabletToolCallsInputBytesTotal => attribute::LABLET_TOOL_CALLS_INPUT_BYTES_TOTAL,
            Self::LabletToolCallsLatencyMsTotal => attribute::LABLET_TOOL_CALLS_LATENCY_MS_TOTAL,
            Self::LabletToolCallsOutputBytesTotal => {
                attribute::LABLET_TOOL_CALLS_OUTPUT_BYTES_TOTAL
            }
            Self::LabletToolCallsTotal => attribute::LABLET_TOOL_CALLS_TOTAL,
            Self::LabletToolCallsTruncated => attribute::LABLET_TOOL_CALLS_TRUNCATED,
            Self::LabletToolCallsUnknown => attribute::LABLET_TOOL_CALLS_UNKNOWN,
            Self::LabletToolsCount => attribute::LABLET_TOOLS_COUNT,
            Self::LabletToolsDigest => attribute::LABLET_TOOLS_DIGEST,
            Self::LabletToolsNames => attribute::LABLET_TOOLS_NAMES,
            Self::LabletTrial => attribute::LABLET_TRIAL,
            Self::ServerAddress => attribute::SERVER_ADDRESS,
            Self::ServerPort => attribute::SERVER_PORT,
            Self::SessionId => attribute::SESSION_ID,
        }
    }
}

/// The template keys of event `lablet.run`, one variant for each. The
/// event holds a template once for each suffix it has a value for.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum EventLabletRunTemplate {
    /// `lablet.tool.calls.<key>`. Conditionally required: One for each tool the run offered and called.
    LabletToolCalls,
    /// `lablet.tool.errors.<key>`. Conditionally required: One for each tool the run offered and called.
    LabletToolErrors,
    /// `lablet.tool.latency_ms.<key>`. Conditionally required: One for each tool the run offered and called.
    LabletToolLatencyMs,
}

impl EventLabletRunTemplate {
    /// Every template, each once.
    pub const ALL: &[Self] = &[
        Self::LabletToolCalls,
        Self::LabletToolErrors,
        Self::LabletToolLatencyMs,
    ];

    /// What the emitted key starts with: a dot and the suffix follow it.
    #[must_use]
    pub const fn prefix(self) -> &'static str {
        match self {
            Self::LabletToolCalls => attribute::LABLET_TOOL_CALLS,
            Self::LabletToolErrors => attribute::LABLET_TOOL_ERRORS,
            Self::LabletToolLatencyMs => attribute::LABLET_TOOL_LATENCY_MS,
        }
    }
}
