// Generated by `cargo xtask weaver generate` from lablet/telemetry/registry/; don't edit.

//! The attribute keys of each span and event, for tests that hold an emitted
//! signal to the registry. A template attribute is listed by its prefix.

use crate::attribute;

/// Keys span `lablet.chat` always carries. It's of kind `client`, named `chat {gen_ai.request.model}`.
pub const SPAN_LABLET_CHAT_REQUIRED: &[&str] = &[
    attribute::GEN_AI_CONVERSATION_ID,
    attribute::GEN_AI_OPERATION_NAME,
    attribute::GEN_AI_PROVIDER_NAME,
    attribute::GEN_AI_REQUEST_MAX_TOKENS,
    attribute::GEN_AI_REQUEST_MODEL,
    attribute::LABLET_ATTEMPT,
    attribute::LABLET_CONFIG_DIGEST,
    attribute::LABLET_REQUEST_BYTES,
    attribute::LABLET_TURN,
    attribute::SESSION_ID,
];

/// Every key span `lablet.chat` may carry.
pub const SPAN_LABLET_CHAT_KEYS: &[&str] = &[
    attribute::ERROR_TYPE,
    attribute::GEN_AI_CONVERSATION_ID,
    attribute::GEN_AI_OPERATION_NAME,
    attribute::GEN_AI_PROVIDER_NAME,
    attribute::GEN_AI_REQUEST_MAX_TOKENS,
    attribute::GEN_AI_REQUEST_MODEL,
    attribute::GEN_AI_REQUEST_REASONING_LEVEL,
    attribute::GEN_AI_REQUEST_SEED,
    attribute::GEN_AI_REQUEST_TEMPERATURE,
    attribute::GEN_AI_RESPONSE_FINISH_REASONS,
    attribute::GEN_AI_RESPONSE_ID,
    attribute::GEN_AI_RESPONSE_MODEL,
    attribute::GEN_AI_USAGE_CACHE_READ_INPUT_TOKENS,
    attribute::GEN_AI_USAGE_CACHE_WRITE_INPUT_TOKENS,
    attribute::GEN_AI_USAGE_INPUT_TOKENS,
    attribute::GEN_AI_USAGE_OUTPUT_TOKENS,
    attribute::LABLET_ATTEMPT,
    attribute::LABLET_CONFIG_DIGEST,
    attribute::LABLET_REQUEST_BYTES,
    attribute::LABLET_TURN,
    attribute::SERVER_ADDRESS,
    attribute::SERVER_PORT,
    attribute::SESSION_ID,
];

/// Keys span `lablet.execute_tool` always carries. It's of kind `internal`, named `execute_tool {gen_ai.tool.name}`.
pub const SPAN_LABLET_EXECUTE_TOOL_REQUIRED: &[&str] = &[
    attribute::GEN_AI_CONVERSATION_ID,
    attribute::GEN_AI_OPERATION_NAME,
    attribute::GEN_AI_TOOL_CALL_ID,
    attribute::GEN_AI_TOOL_NAME,
    attribute::GEN_AI_TOOL_TYPE,
    attribute::LABLET_CONFIG_DIGEST,
    attribute::LABLET_TOOL_INPUT_BYTES,
    attribute::LABLET_TOOL_IS_ERROR,
    attribute::LABLET_TOOL_OUTPUT_BYTES,
    attribute::LABLET_TOOL_SOURCE,
    attribute::LABLET_TURN,
    attribute::SESSION_ID,
];

/// Every key span `lablet.execute_tool` may carry.
pub const SPAN_LABLET_EXECUTE_TOOL_KEYS: &[&str] = &[
    attribute::ERROR_TYPE,
    attribute::GEN_AI_CONVERSATION_ID,
    attribute::GEN_AI_OPERATION_NAME,
    attribute::GEN_AI_TOOL_CALL_ID,
    attribute::GEN_AI_TOOL_DESCRIPTION,
    attribute::GEN_AI_TOOL_NAME,
    attribute::GEN_AI_TOOL_TYPE,
    attribute::JSONRPC_REQUEST_ID,
    attribute::LABLET_CONFIG_DIGEST,
    attribute::LABLET_TOOL_INPUT_BYTES,
    attribute::LABLET_TOOL_IS_ERROR,
    attribute::LABLET_TOOL_OUTPUT_BYTES,
    attribute::LABLET_TOOL_SOURCE,
    attribute::LABLET_TURN,
    attribute::MCP_METHOD_NAME,
    attribute::MCP_PROTOCOL_VERSION,
    attribute::MCP_SESSION_ID,
    attribute::NETWORK_TRANSPORT,
    attribute::RPC_RESPONSE_STATUS_CODE,
    attribute::SESSION_ID,
];

/// Keys span `lablet.invoke_agent` always carries. It's of kind `internal`, named `invoke_agent {gen_ai.agent.name}`.
pub const SPAN_LABLET_INVOKE_AGENT_REQUIRED: &[&str] = &[
    attribute::GEN_AI_AGENT_NAME,
    attribute::GEN_AI_AGENT_VERSION,
    attribute::GEN_AI_CONVERSATION_ID,
    attribute::GEN_AI_OPERATION_NAME,
    attribute::GEN_AI_REQUEST_MODEL,
    attribute::GEN_AI_USAGE_CACHE_READ_INPUT_TOKENS,
    attribute::GEN_AI_USAGE_CACHE_WRITE_INPUT_TOKENS,
    attribute::GEN_AI_USAGE_INPUT_TOKENS,
    attribute::GEN_AI_USAGE_OUTPUT_TOKENS,
    attribute::LABLET_CONFIG_DIGEST,
    attribute::LABLET_RUN_STOP_REASON,
    attribute::LABLET_RUN_TURNS,
    attribute::LABLET_TOOL_CALLS_TOTAL,
    attribute::SESSION_ID,
];

/// Every key span `lablet.invoke_agent` may carry.
pub const SPAN_LABLET_INVOKE_AGENT_KEYS: &[&str] = &[
    attribute::ERROR_TYPE,
    attribute::GEN_AI_AGENT_NAME,
    attribute::GEN_AI_AGENT_VERSION,
    attribute::GEN_AI_CONVERSATION_ID,
    attribute::GEN_AI_OPERATION_NAME,
    attribute::GEN_AI_REQUEST_MODEL,
    attribute::GEN_AI_USAGE_CACHE_READ_INPUT_TOKENS,
    attribute::GEN_AI_USAGE_CACHE_WRITE_INPUT_TOKENS,
    attribute::GEN_AI_USAGE_INPUT_TOKENS,
    attribute::GEN_AI_USAGE_OUTPUT_TOKENS,
    attribute::LABLET_CONFIG_DIGEST,
    attribute::LABLET_RUN_COST_USD,
    attribute::LABLET_RUN_STOP_REASON,
    attribute::LABLET_RUN_TURNS,
    attribute::LABLET_TOOL_CALLS_TOTAL,
    attribute::SESSION_ID,
];

/// Name of event `gen_ai.client.inference.operation.details`.
pub const EVENT_GEN_AI_CLIENT_INFERENCE_OPERATION_DETAILS_NAME: &str =
    "gen_ai.client.inference.operation.details";

/// Keys event `gen_ai.client.inference.operation.details` always carries.
pub const EVENT_GEN_AI_CLIENT_INFERENCE_OPERATION_DETAILS_REQUIRED: &[&str] = &[
    attribute::GEN_AI_CONVERSATION_ID,
    attribute::GEN_AI_OPERATION_NAME,
    attribute::LABLET_CONFIG_DIGEST,
    attribute::LABLET_TURN,
    attribute::SESSION_ID,
];

/// Every key event `gen_ai.client.inference.operation.details` may carry.
pub const EVENT_GEN_AI_CLIENT_INFERENCE_OPERATION_DETAILS_KEYS: &[&str] = &[
    attribute::GEN_AI_CONVERSATION_ID,
    attribute::GEN_AI_INPUT_MESSAGES,
    attribute::GEN_AI_OPERATION_NAME,
    attribute::GEN_AI_OUTPUT_MESSAGES,
    attribute::GEN_AI_SYSTEM_INSTRUCTIONS,
    attribute::GEN_AI_TOOL_CALL_ARGUMENTS,
    attribute::GEN_AI_TOOL_CALL_ID,
    attribute::GEN_AI_TOOL_CALL_RESULT,
    attribute::GEN_AI_TOOL_NAME,
    attribute::LABLET_CONFIG_DIGEST,
    attribute::LABLET_TURN,
    attribute::SESSION_ID,
];

/// Name of event `gen_ai.client.operation.exception`.
pub const EVENT_GEN_AI_CLIENT_OPERATION_EXCEPTION_NAME: &str = "gen_ai.client.operation.exception";

/// Keys event `gen_ai.client.operation.exception` always carries.
pub const EVENT_GEN_AI_CLIENT_OPERATION_EXCEPTION_REQUIRED: &[&str] = &[
    attribute::EXCEPTION_MESSAGE,
    attribute::EXCEPTION_TYPE,
    attribute::GEN_AI_CONVERSATION_ID,
    attribute::GEN_AI_OPERATION_NAME,
    attribute::GEN_AI_PROVIDER_NAME,
    attribute::GEN_AI_REQUEST_MODEL,
    attribute::LABLET_ATTEMPT,
    attribute::LABLET_CONFIG_DIGEST,
    attribute::LABLET_TURN,
    attribute::SESSION_ID,
];

/// Every key event `gen_ai.client.operation.exception` may carry.
pub const EVENT_GEN_AI_CLIENT_OPERATION_EXCEPTION_KEYS: &[&str] = &[
    attribute::EXCEPTION_MESSAGE,
    attribute::EXCEPTION_TYPE,
    attribute::GEN_AI_CONVERSATION_ID,
    attribute::GEN_AI_OPERATION_NAME,
    attribute::GEN_AI_PROVIDER_NAME,
    attribute::GEN_AI_REQUEST_MODEL,
    attribute::LABLET_ATTEMPT,
    attribute::LABLET_CONFIG_DIGEST,
    attribute::LABLET_TURN,
    attribute::SESSION_ID,
];

/// Name of event `lablet.retry`.
pub const EVENT_LABLET_RETRY_NAME: &str = "lablet.retry";

/// Keys event `lablet.retry` always carries.
pub const EVENT_LABLET_RETRY_REQUIRED: &[&str] = &[
    attribute::LABLET_ATTEMPT,
    attribute::LABLET_RETRY_WILL_RETRY,
];

/// Every key event `lablet.retry` may carry.
pub const EVENT_LABLET_RETRY_KEYS: &[&str] = &[
    attribute::LABLET_ATTEMPT,
    attribute::LABLET_RETRY_BACKOFF_MS,
    attribute::LABLET_RETRY_WILL_RETRY,
];

/// Name of event `lablet.run`.
pub const EVENT_LABLET_RUN_NAME: &str = "lablet.run";

/// Keys event `lablet.run` always carries.
pub const EVENT_LABLET_RUN_REQUIRED: &[&str] = &[
    attribute::GEN_AI_AGENT_NAME,
    attribute::GEN_AI_AGENT_VERSION,
    attribute::GEN_AI_CONVERSATION_ID,
    attribute::GEN_AI_PROVIDER_NAME,
    attribute::GEN_AI_REQUEST_MAX_TOKENS,
    attribute::GEN_AI_REQUEST_MODEL,
    attribute::GEN_AI_RESPONSE_FINISH_REASONS,
    attribute::GEN_AI_USAGE_CACHE_READ_INPUT_TOKENS,
    attribute::GEN_AI_USAGE_CACHE_WRITE_INPUT_TOKENS,
    attribute::GEN_AI_USAGE_INPUT_TOKENS,
    attribute::GEN_AI_USAGE_OUTPUT_TOKENS,
    attribute::LABLET_CONFIG_DIGEST,
    attribute::LABLET_MCP_SERVERS,
    attribute::LABLET_PROMPT_SYSTEM_BYTES,
    attribute::LABLET_PROMPT_USER_BYTES,
    attribute::LABLET_PROVIDER_CALLS,
    attribute::LABLET_PROVIDER_LATENCY_MS_MAX,
    attribute::LABLET_PROVIDER_LATENCY_MS_TOTAL,
    attribute::LABLET_PROVIDER_RETRIES,
    attribute::LABLET_RESULT_HAS_STRUCTURED,
    attribute::LABLET_RESULT_TEXT_BYTES,
    attribute::LABLET_RUN_COMPLETION_MODE,
    attribute::LABLET_RUN_DURATION_MS,
    attribute::LABLET_RUN_MAX_TURNS,
    attribute::LABLET_RUN_STOP_REASON,
    attribute::LABLET_RUN_TIMEOUT_MS,
    attribute::LABLET_RUN_TURNS,
    attribute::LABLET_SKILLS_COUNT,
    attribute::LABLET_TOOL_CALLS_ERRORS,
    attribute::LABLET_TOOL_CALLS_INPUT_BYTES_TOTAL,
    attribute::LABLET_TOOL_CALLS_LATENCY_MS_TOTAL,
    attribute::LABLET_TOOL_CALLS_OUTPUT_BYTES_TOTAL,
    attribute::LABLET_TOOL_CALLS_TOTAL,
    attribute::LABLET_TOOLS_COUNT,
    attribute::LABLET_TOOLS_NAMES,
    attribute::SESSION_ID,
];

/// Every key event `lablet.run` may carry.
pub const EVENT_LABLET_RUN_KEYS: &[&str] = &[
    attribute::ERROR_TYPE,
    attribute::GEN_AI_AGENT_NAME,
    attribute::GEN_AI_AGENT_VERSION,
    attribute::GEN_AI_CONVERSATION_ID,
    attribute::GEN_AI_PROVIDER_NAME,
    attribute::GEN_AI_REQUEST_MAX_TOKENS,
    attribute::GEN_AI_REQUEST_MODEL,
    attribute::GEN_AI_REQUEST_REASONING_LEVEL,
    attribute::GEN_AI_REQUEST_SEED,
    attribute::GEN_AI_RESPONSE_FINISH_REASONS,
    attribute::GEN_AI_USAGE_CACHE_READ_INPUT_TOKENS,
    attribute::GEN_AI_USAGE_CACHE_WRITE_INPUT_TOKENS,
    attribute::GEN_AI_USAGE_INPUT_TOKENS,
    attribute::GEN_AI_USAGE_OUTPUT_TOKENS,
    attribute::LABLET_CONFIG_DIGEST,
    attribute::LABLET_MCP_SERVERS,
    attribute::LABLET_PROMPT_SYSTEM_BYTES,
    attribute::LABLET_PROMPT_USER_BYTES,
    attribute::LABLET_PROVIDER_CALLS,
    attribute::LABLET_PROVIDER_LATENCY_MS_MAX,
    attribute::LABLET_PROVIDER_LATENCY_MS_TOTAL,
    attribute::LABLET_PROVIDER_RETRIES,
    attribute::LABLET_RESULT_HAS_STRUCTURED,
    attribute::LABLET_RESULT_STRUCTURED,
    attribute::LABLET_RESULT_TEXT,
    attribute::LABLET_RESULT_TEXT_BYTES,
    attribute::LABLET_RUN_COMPLETION_MODE,
    attribute::LABLET_RUN_COST_USD,
    attribute::LABLET_RUN_DURATION_MS,
    attribute::LABLET_RUN_ERROR,
    attribute::LABLET_RUN_MAX_TURNS,
    attribute::LABLET_RUN_STOP_REASON,
    attribute::LABLET_RUN_TIMEOUT_MS,
    attribute::LABLET_RUN_TRANSCRIPT_PATH,
    attribute::LABLET_RUN_TURNS,
    attribute::LABLET_SKILLS_COUNT,
    attribute::LABLET_TOOL_CALLS,
    attribute::LABLET_TOOL_ERRORS,
    attribute::LABLET_TOOL_LATENCY_MS,
    attribute::LABLET_TOOL_CALLS_ERRORS,
    attribute::LABLET_TOOL_CALLS_INPUT_BYTES_TOTAL,
    attribute::LABLET_TOOL_CALLS_LATENCY_MS_TOTAL,
    attribute::LABLET_TOOL_CALLS_OUTPUT_BYTES_TOTAL,
    attribute::LABLET_TOOL_CALLS_TOTAL,
    attribute::LABLET_TOOLS_COUNT,
    attribute::LABLET_TOOLS_NAMES,
    attribute::SESSION_ID,
];
