[package]
name = "lablet-otel-env"
description = "The specification's parsing of the OpenTelemetry environment's variables"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
lablet-config.workspace = true
tracing.workspace = true

[dev-dependencies]
tracing-subscriber.workspace = true
